"""Tests for build_weekly_report and send_telegram_report — sovereign.reporting.weekly_report."""
from __future__ import annotations

import asyncio
import pathlib
from datetime import datetime, timezone


from sovereign.reporting.weekly_report import (
    _iso_week,
    build_weekly_report,
    send_telegram_report,
)


def test_build_returns_string(tmp_path: pathlib.Path):
    result = build_weekly_report(data_dir=str(tmp_path))
    assert isinstance(result, str)
    assert len(result) > 0


def test_build_contains_header(tmp_path: pathlib.Path):
    result = build_weekly_report(data_dir=str(tmp_path))
    assert "SOVEREIGN Weekly Report" in result


def test_build_contains_week(tmp_path: pathlib.Path):
    result = build_weekly_report(data_dir=str(tmp_path))
    assert "W" in result
    week = _iso_week()
    assert week in result


def test_build_contains_footer(tmp_path: pathlib.Path):
    result = build_weekly_report(data_dir=str(tmp_path))
    assert "Generated by SOVEREIGN AI OS" in result


def test_send_telegram_no_token():
    result = asyncio.run(send_telegram_report("test", token="", chat_id=0))
    assert result is False


def test_iso_week():
    expected = datetime.now(timezone.utc).strftime("%Y-W%V")
    assert _iso_week() == expected
