"""DecisionScienceLab — decision quality, cognitive bias detection, option analysis."""
from __future__ import annotations

from sovereign.labs.labs_framework import LabsFramework


class DecisionScienceLab(LabsFramework):
    lab_id = "decision_science"
    lab_name = "Decision Science Lab"
    description = "Decision quality research: cognitive bias detection, option generation, regret minimization."
    agents = ["option_generator", "devils_advocate", "second_opinion", "regret_minimizer",
              "tradeoff_agent", "reversibility_agent", "decision_quality"]
    tools = ["memory_tool", "code_exec"]
    dataset_description = "Decision logs, outcome tracking, bias detection reports, option analyses."
    benchmarks = {"decision_quality_score": 0.80, "bias_detection_rate": 0.75}
    output_standards = {"decision_report": "Structured decision brief with options, risks, and recommendation"}
    requires_human_review = False
    model = "claude-opus-4-6"
    experiment_templates = [
        {
            "name": "Option Generation — AI Breadth vs Human Brainstorming",
            "description": "Compare number and quality of decision options generated by AI option_generator vs human brainstorming session.",
            "hypothesis": {
                "statement": "AI option generation produces ≥2x more distinct viable options than unaided human brainstorming",
                "metric": "decision_quality_score",
                "success_threshold": 0.80,
                "baseline": 0.55,
            },
            "control_config": {"method": "human_brainstorm", "participants": 3},
            "treatment_config": {"method": "ai_option_generator", "dimensions": 8, "adversarial_check": True},
            "tags": ["decision", "options", "quality"],
        },
        {
            "name": "Bias Detection — Pre-Mortem vs Post-Decision Review",
            "description": "Measure bias incidence rate in decisions reviewed with pre-mortem analysis vs standard post-decision review.",
            "hypothesis": {
                "statement": "Pre-mortem analysis reduces identifiable cognitive bias incidence by ≥25%",
                "metric": "bias_detection_rate",
                "success_threshold": 0.75,
                "baseline": 0.50,
            },
            "control_config": {"review": "post_decision"},
            "treatment_config": {"review": "pre_mortem", "bias_list": ["overconfidence", "groupthink", "sunk_cost"]},
            "tags": ["decision", "bias", "pre_mortem"],
        },
        {
            "name": "Regret Minimisation — 10-10-10 Rule Application",
            "description": "Test whether applying the 10-10-10 temporal regret framework improves long-term satisfaction scores for major decisions.",
            "hypothesis": {
                "statement": "10-10-10 rule application improves 6-month post-decision satisfaction by ≥20%",
                "metric": "decision_quality_score",
                "success_threshold": 0.80,
                "baseline": 0.60,
            },
            "control_config": {"framework": "intuitive"},
            "treatment_config": {"framework": "10_10_10", "time_horizons": [10, 10 * 30, 10 * 365]},
            "tags": ["decision", "regret", "framework"],
        },
    ]

    def __init__(self, data_path: str = "data/labs/decision_experiments.json") -> None:
        super().__init__(data_path=data_path)

    def describe(self) -> dict:
        return {"lab_id": self.lab_id, "lab_name": self.lab_name, "agents": self.agents,
                "tools": self.tools, "requires_human_review": self.requires_human_review, "model": self.model}

lab = DecisionScienceLab()
